### PR TITLE
Update README.md to address #462

### PR DESCRIPTION
**Pull request by NQNStudios**
Could be made more concise, and might not be git beginner-friendly enough, but I made some edits that should make our recurring problem stated in #462 less common by being extremely explicit and using bold/capitalized text and a heading.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
> You can't use the vcpkg installation that comes with Visual Studio for
these commands.

…huh? Why not?

**Comment by NQNStudios** [comment]
Vcpkg has two modes: manifest mode (which we use in the CI to lock the
dependency versions) and classic mode (which we are telling people to use
here). In Visual Studio 2022 Community edition I found out yesterday that
they’ve disabled classic mode in the built-in vcpkg.

So an alternative here would be to change this instruction to tell them to
use manifest mode. For some reason, we didn’t make that change in the docs
when we made it in the CI. I don’t remember if there was a good reason.

**Review by CelticMinstrel — COMMENTED** [review]
> So an alternative here would be to change this instruction to tell them to
> use manifest mode.

What does that actually entail? How would the install commands differ?

**Comment by NQNStudios** [comment]
As it happens, I think the install command would get simpler, with a caveat that you must call it from inside proj/vs2017 or proj\vs2013.

`C:\Users\natqu\repos\cboe\proj\vs2017>vcpkg install --triplet=x64-windows`

And this would help us avoid new contributors getting a new version of boost that scons can't find.

**Comment by NQNStudios** [comment]
I'm gonna go ahead and make that change.

**Pull request merged**
