### PR TITLE
Fosnola's fix #101

### LINKED ISSUE #101: Town boundary width and height are swapped
Towns that do not have their boundaries drawn in a square have redrawn themselves
e.g. if it is 28x30, it becomes 30x28, and moves the party out of town when it shouldn't.

---
This is an item logged from the To-Do and was originally reported by BainIhrno. If you are familiar with or can recreate this bug, please provide details here.

### PR DESCRIPTION
**Pull request by NQNStudios**
I've cherry-picked and amended (to remove extraneous changes) one of the commit's @fosnola said fixes issue #101, and after testing, it seems that the fix works. (However, I can in no way guarantee that it doesn't break anything else.)

There was an additional commit fosnola mentioned, https://github.com/fosnola/cboe/commit/d63b089018b8ceee8e6126bb02b575a65c2fe867 , but I looked through that one and I can't tell how it's related to town boundaries. Also it has merge conflicts against our master branch, so I thought I'd leave it alone for now.

Edit: I also don't know how it could break legacy saves, or if that other commit was to fix that potential problem.

### CODE REVIEW

**Comment by NQNStudios** [comment]
This bug would actually be a good candidate for having a unit test.

**Comment by CelticMinstrel** [comment]
Any ideas on what that unit test could look like? We could add it in this PR as well.

**Comment by NQNStudios** [comment]
It could load the legacy test scenarios and check the town boundary
rectangles directly to make assertions.

Where would you want me to put test scenarios in the repository?

**Comment by CelticMinstrel** [comment]
I guess they could go in rsrc/ in a new folder, like test or test-scenarios or something like that. The other option would be in test/files/.

**Comment by NQNStudios** [comment]
Closed in favor of #441

**Pull request closed without merging**
