### PR TITLE
Recharge spell

### PR DESCRIPTION
**Pull request by CelticMinstrel**

### CODE REVIEW

**Comment by NQNStudios** [comment]
@CelticMinstrel is this at all likely to break the magic recording/replay I have implemented in #416 ?

**Comment by NQNStudios** [comment]
I also noticed, in the help window for the party status screen, the Normal Speed icon is listed:

Screenshot 2024-08-31 at 1 23 18 PM

We'll wanna take that out along with the icon itself.

**Comment by CelticMinstrel** [comment]
> @CelticMinstrel is this at all likely to break the magic recording/replay I have implemented in #416 ?

I don't think it would break any of the things you already implemented, but pressing space during `MODE_ITEM_TARGET` probably needs a new replay action in this branch.

> I also noticed, in the help window for the party status screen, the Normal Speed icon is listed:

Hmm… flying, detect life, stealth, and firewalk don't really belong there either, as they appear on the area bar rather than the party status screen. But I don't have any better place to put them…

> We'll wanna take that out along with the icon itself.

I'm going to leave the icon itself in place in the graphics sheet, but removing references to it, yes.

**Comment by NQNStudios** [comment]
Are you still working on this one? If it’s finished, does it make more
sense to merge this first or finish out and merge the replay PR first?

**Comment by CelticMinstrel** [comment]
I still have a bit to do on this one – I want to add the chance of melting an item if you try to overcharge it.

**Comment by CelticMinstrel** [comment]
Okay, I think I've finished everything I want to do here. Just have to make sure it's all replayable… and there's also one TODO comment that I might address.

**Comment by NQNStudios** [comment]
I haven't reviewed it or anything, but as far as I'm concerned, it's a good time for you to merge changes. I'm focused on the automated builds right now so it could be a little while before I make more PRs.

**Comment by CelticMinstrel** [comment]
I decided to just go ahead and merge. I still have to make sure the identify and recharge spells are properly replayable, and probably add a way for them to auto-complete, but I'll get to that a bit later.

**Pull request merged**
