### PR TITLE
Replay system small fix

### PR DESCRIPTION
**Pull request by NQNStudios**

### CODE REVIEW

**Comment by NQNStudios** [comment]
I was gonna put more into this PR but I haven't decided what to do next & this one commit is definitely correct and needed so I don't want to hold it up.

**Comment by CelticMinstrel** [comment]
So, it is correct to poll events when replaying?

**Comment by NQNStudios** [comment]
When the replay runs out of actions to replay without quitting the app,
yeah.

**Comment by CelticMinstrel** [comment]
Hmm. I would've expected `replaying` to become false in that case, but alright.

**Pull request merged**
